name: Docker Image CI

on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:

  build-kinetic:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build the code for Ubuntu 16
      run: docker build . --file ./scripts/docker/astrobee_kinetic.Dockerfile

  build-melodic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build the code for Ubuntu 18
      run: docker build . --file ./scripts/docker/astrobee_melodic.Dockerfile
