# Push the latest-base Docker images without doing a release. Called
# manually only when needed (basically, when we push a change that
# affects the base image on the develop branch).

name: Docker push latest base

on: ['workflow_dispatch']

jobs:

  build-xenial:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build base for Ubuntu 16 Xenial
      run: ./scripts/docker/build.sh --xenial astrobee_base

    - name: Build code for Ubuntu 16 Xenial
      run: ./scripts/docker/build.sh --xenial astrobee

    - name: Test code
      run: ./scripts/docker/build.sh --xenial test_astrobee

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker image
      run: |
        docker tag astrobee/astrobee:latest-base-ubuntu16.04 ghcr.io/${{ github.repository_owner }}/astrobee:latest-base-ubuntu16.04
        docker push ghcr.io/${{ github.repository_owner }}/astrobee:latest-base-ubuntu16.04

  build-bionic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build base for Ubuntu 18 Bionic
      run: ./scripts/docker/build.sh --bionic astrobee_base

    - name: Build code for Ubuntu 18 Bionic
      run: ./scripts/docker/build.sh --bionic astrobee

    - name: Test code
      run: ./scripts/docker/build.sh --bionic test_astrobee

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker image
      run: |
        docker tag astrobee/astrobee:latest-base-ubuntu18.04 ghcr.io/${{ github.repository_owner }}/astrobee:latest-base-ubuntu18.04
        docker push ghcr.io/${{ github.repository_owner }}/astrobee:latest-base-ubuntu18.04

  build-focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build base for Ubuntu 20 Focal
      run: ./scripts/docker/build.sh --focal astrobee_base

    - name: Build code for Ubuntu 20 Focal
      run: ./scripts/docker/build.sh --focal astrobee

    - name: Test code
      run: ./scripts/docker/build.sh --focal test_astrobee

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker image
      run: |
        docker tag astrobee/astrobee:latest-base-ubuntu20.04 ghcr.io/${{ github.repository_owner }}/astrobee:latest-base-ubuntu20.04
        docker push ghcr.io/${{ github.repository_owner }}/astrobee:latest-base-ubuntu20.04
