# Build documentation and commit to gh-pages branch.

name: Build and Push Documentation to gh-pages Branch

on:
  push:
    branches: ['develop']

jobs:
  build_and_push_docs:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: repo/
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: docs/
        ref: gh-pages
    - name: Build docker image with dependencies + build docs
      run: docker build repo -f repo/scripts/docker/documentation.Dockerfile
                                 -t astrobee:documentation

    - name: Replace old documentation with new
      run: |
        [ -d docs ] || mkdir docs
        [ -d docs/html ] && rm -r docs/html
        docker cp $(docker create --rm astrobee:documentation):/repo/doc/html docs/html

    - name: Commit and Push
      run: |
        cd docs
        git add --all html/
        EMAIL=`git show -s --format='%ae' HEAD`
        NAME=`git show -s --format='%an' HEAD`
        git config user.email "$EMAIL"
        git config user.name "$NAME"
        { git commit -m "Automatic update for $GITHUB_SHA." || true; }
        git push origin gh-pages
