# Check for lint error and auto correct them

name: Check for C++ lint errors

on: ['push', 'pull_request']

jobs:
  lint_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check repo for lint errors
      run: ./scripts/git/cpplint_repo.py .

name: Check for python lint errors

on: ['push', 'pull_request']

jobs:
  lint_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install linters
      run: |
        pip install black
        pip install isort

    - name: Run linters
      run: |
        black . --diff --extend-exclude cmake
        isort !(cmake) --profile black
