# Check for lint error and auto correct them

name: Build jar messages

on: ['push', 'pull_request']

jobs:
  install_dependencies:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Astrobee
      uses: actions/checkout@v2
      with:
        repository: nasa/astrobee
        path: astrobee/

    - name: Build image astrobee/astrobee:msgs-ubuntu16.04
      run: docker build astrobee -f astrobee/scripts/docker/astrobee_msgs.Dockerfile
                                 --build-arg UBUNTU_VERSION=16.04
                                 --build-arg ROS_VERSION=kinetic
                                 --build-arg PYTHON=''
                                 -t astrobee/astrobee:msgs-ubuntu16.04

    - name: Build image astrobee/astrobee:latest-msgs-jar-ubuntu16.04
      run: docker build astrobee -f astrobee/scripts/docker/build_msgs_jar.Dockerfile
                              --build-arg UBUNTU_VERSION=16.04
                              --build-arg ROS_VERSION=kinetic
                              --build-arg PYTHON=''
                              --build-arg REPO=astrobee
                              -t ghcr.io/${{ github.repository_owner }}/astrobee:latest-msgs-jar

    - name: Copy jar files
      run: |
        docker cp $(docker create --rm ghcr.io/${{ github.repository_owner }}/astrobee:latest-msgs-jar):/src/msgs/devel/share/maven/ .
        find maven -name *.jar

    - name: Log in to registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

        echo "head_ref: ${{ github.head_ref }}"

    - name: Push Docker image if master or develop
      run: >
        if [[ "${{ github.repository_owner }}" = "nasa" ]]; then \
          if [[ "${{ github.head_ref }}" = "develop" ]]; then 
            docker push ghcr.io/${{ github.repository_owner }}/astrobee:latest-msgs-jar;
          fi;
          if [[ "${{ github.head_ref }}" = "master" ]]; then
            export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`;
            docker tag ghcr.io/${{ github.repository_owner }}/astrobee:latest-msgs-jar ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-msgs-jar
            docker push ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-msgs-jar;
          fi;
        fi;
